version: "3"

services:
  mongodb:
    container_name: ${APP_NAME}-mongo
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./mongodb:/data/db
