version: "3"

services:
  mongodb:
    container_name: ${APP_NAME}-mongo
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./mongodb:/data/db

  app:
    container_name: ${APP_NAME}-app
    image: ${APP_NAME}:${APP_VERSION}
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    depends_on:
      - mongodb
    command: npm run start:prod
    ports:
      - ${PORT}:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
